#!/bin/bash

# this is intended to operate on a lerna mono repo generated by zotoio/generator-mono-serverless

set -e

cd /usr/workspace

source ./clone.sh

if [ -n "$GIT_PR_ID" ]; then
    source fetch-pullrequest.sh
else
    if [ -n "$GIT_PUSH_BRANCHNAME" ]; then
        cd /usr/workspace/clone
        git checkout $GIT_PUSH_BRANCHNAME
    fi
fi

cd /usr/workspace/
export BUILD_COMMAND=yarn
source ./deps.sh
source ./build.sh

echo "looks like we need to deploy $SLS_AFFECTED_PACKAGES .."

export IFS=","
for pack in $SLS_AFFECTED_PACKAGES; do
    cd /usr/workspace/clone/packages/$pack
    yarn sls-deploy
done

echo "ALL DEPLOYS SUCCESSFUL"